#!/bin/bash

case "$1" in
  define)
    curl -s -G "localhost:3000/templates/definition" \
    --data-urlencode "path=$2" \
    --data-urlencode "line=$3" \
    --data-urlencode "column=$4" \
    --data-urlencode "attr=$5" \
    --data-urlencode "format=compact"
    ;;
  alternate)
    curl -s -G "localhost:3000/files/alternate" \
      --data-urlencode "path=$2" \
      --data-urlencode "format=compact"
    ;;
  parents)
    curl -s -G "localhost:3000/templates/parents" \
      --data-urlencode "path=$2" \
      --data-urlencode "format=compact"
    ;;
  invokedAttr)
    curl -s -G "localhost:3000/templates/invokedAttr" \
      --data-urlencode "path=$2" \
      --data-urlencode "line=$3" \
      --data-urlencode "column=$4" \
      --data-urlencode "attr=$5" \
      --data-urlencode "format=compact"
    ;;
  checkTemplate)
    curl -s -G "localhost:3000/templates/check" \
      --data-urlencode "path=$2" \
      --data-urlencode "format=compact"
    ;;
  moduleNames)
    curl -s -G "localhost:3000/modules" \
      --data-urlencode "type=$2" \
      --data-urlencode "format=compact"
    ;;
  module)
    curl -s -G "localhost:3000/module" \
      --data-urlencode "moduleName=$2" \
      --data-urlencode "format=compact"
    ;;
  entry)
      curl -s -G "localhost:3000/entry" \
           --data-urlencode "path=$2" \
           --data-urlencode "line=$3" \
           --data-urlencode "column=$4" \
      ;;
  propNode)
      curl -s -G "localhost:3000/prop_node" \
           --data-urlencode "path=$2" \
           --data-urlencode "line=$3" \
           --data-urlencode "column=$4" \
          ;;
  parentNodes)
      curl -s -G "localhost:3000/parents" \
           --data-urlencode "path=$2" \
           --data-urlencode "line=$3" \
           --data-urlencode "column=$4" \
          ;;
esac
